### ISSUE TITLE
MapEnvelope.TryGetValue fail because the collection is readonly

### ISSUE THREAD

**Issue by Orwel** [icarus-consulting/Yaapii.Atoms#238]
### Expected Behavior
MapEnvelope.TryGetValue try get the value.

### Actual Behavior
Map.Envelope.TryGetValue fail because the collection is readonly.

### Steps to reproduce the behavior
```C#
object outValue
new MapEnvelope<int, int>(new Dictionary<int, int>()).TryGetValue(0, outValue);
```

### The log given by the failure.
```
Error Message:
 Yaapii.Atoms.Fail.UnsupportedOperationException : Not supported, it's a read-only map
Stack Trace:
   at Yaapii.Atoms.Map.MapEnvelope`2.TryGetValue(Key key, Value& value) in C:\Users\Orwel\Source\Repos\Yaapii.Atoms\src\Yaapii.Atoms\Map\MapEnvelope.cs:line 173
   at Yaapii.Atoms.Map.MapNoNulls`2.TryGetValue(Key key, Value& value) in C:\Users\Orwel\Source\Repos\Yaapii.Atoms\src\Yaapii.Atoms\Map\MapNoNulls.cs:line 194
   ...
```

### Mention any other details that might be useful
The method TryGetValue read a value. I don't understand why the method fail with readonly exception.
Did i miss some part?

**Comment by Meerownymous** [comment]
You are right, its a bug. Feel free to fix it :)
